### ISSUE TITLE
Yaml based config.

### ISSUE THREAD

**Issue by jdpribula** [lindell/multi-gitter#142]
It would nice to be able to feed MG a yaml(s) with a set of jobs to run instead of having to specify each flag on the commandline. This would be beneficial for running these jobs many times or scheduling them.

Example:
```
---
update_something_one:
  script: job_1.py
  platform: "gitlab"
  groups: "gitlab/group/path" 
  include_subgroups: True
  commit_message: "Update something" 
  branch_name: "hotfix/update-something"
  merge_request:
    body: "Update something body"
    title: "MR title update something"
  dry_run: True
  
bin_true:
  script: bin_true.sh
  platform: "gitlab"
  groups: "gitlab/some/other/path" 
  commit_message: "Run second job" 
  branch_name: "hotfix/second job"
  merge_request:
    body: "Try second job"
    title: "Second MR"
```

Then you would run:
```
multi-gitter run -y path/to/job.yaml
```
